[package]
name = "resume"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "site"
path = "src/site.rs"

[[bin]]
name = "sdf_gen"
path = "src/sdf_gen.rs"


[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = {version = "*", features = ["wayland", "dynamic"]}


